---
apiVersion: v1
data:
  default.conf: |+
    limit_conn_zone $server_name zone=global:10m;
    limit_conn_status 503;
    
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location /ping {
            limit_conn global 3;
            proxy_pass http://127.0.0.1:5000;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-sidecar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slow-app
  name: slow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slow-app
  strategy: {}
  template:
    metadata:
      labels:
        app: slow-app
    spec:
      containers:
      - image: slow-app:latest
        name: slow-app
        imagePullPolicy: Never
        resources: {}
      - image: nginx:1.22.0-alpine
        name: nginx
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: default-conf
            subPath: default.conf
        resources: {}
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: default.conf
                path: default.conf
            name: nginx-sidecar
          name: default-conf
status: {}
