---
apiVersion: v1
kind: Service
metadata:
  name: slow-app
  labels:
    app: slow-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31313
  selector:
    app: slow-app

